theme: jekyll-theme-slate
title: Daniel Rhoda's research website
description: I am an evolutionary biologist using and developing quantitative methods to understand patterns of adaptation and constraint through deep time.
